/* Copyright 2020 Sebastian Achim Mueller */
#ifndef MLISP_CONSTANTS_H_
#define MLISP_CONSTANTS_H_

#define MLISP_DEFAULT_SIMULATION_TRUTH -1
#define MLISP_NIGHT_SKY_BACKGROUND -100
#define MLISP_CONVERTER_ACCIDENTAL -201
#define MLISP_CONVERTER_CROSSTALK -202

#define MLISP_NUM_TIME_SLICES 100
#define MLISP_NEXT_CHANNEL_MARKER 255

#endif
