/* Copyright 2020 Sebastian Achim Mueller */
#ifndef MLIES_CONSTANTS_H_
#define MLIES_CONSTANTS_H_

#define MLIES_DEFAULT_SIMULATION_TRUTH -1
#define MLIES_NIGHT_SKY_BACKGROUND -100
#define MLIES_CONVERTER_ACCIDENTAL -201
#define MLIES_CONVERTER_CROSSTALK -202

#define MLIES_NUM_TIME_SLICES 100
#define MLIES_NEXT_CHANNEL_MARKER 255

#endif
